# Permalinks
permalink:           /anotherblog/:title

# Setup
title:               '笋爸的博客'
url:                 https://hongyuanh.github.io/anotherblog/
tagline:             '所想与所得'
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Hongyuan Huang
  url:               
  email:             

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/HongyuanH/anotherblog.git
